### ISSUE TITLE
installing got errors

### ISSUE THREAD

**Issue by ibrainventures** [codingstones/tmdb-quasar#1]
what means that  './secrets' error

?

------
yarn run v1.3.2
warning package.json: No license field
$ node build/script.dev.js mat
module.js:544
    throw err;
    ^

Error: Cannot find module './secrets'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/developer/quasartmdb/tmdb-quasar/config/prod.env.js:1:79)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by agualis** [comment]
I've updated README with instructions:
You will need to register in [themoviedb](https://www.themoviedb.org/documentation/api) to create your API_KEY, then you need to rename /config/secrets2.js to /config/secret.js and paste your API_KEY there.

**Comment by ibrainventures** [comment]
works now perfect ! Good work :-)
